#use_frameworks!

platform :ios, '8.0'

target 'YanFirstCommonKit_Example' do
  pod 'YanFirstCommonKit', :path => '../'

  target 'YanFirstCommonKit_Tests' do
    inherit! :search_paths

    
  end
end
